### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by gzzen** [calamari99/dsci-310-group-12-dreamteam#19]
- [ ] Please improve the modularity of function design, i.e., the function `clean_data` should only perform operations on cleaning the dataset, and is not responsible for printing messages (-1)
- [ ] Please consider reducing the coupling of functions. Both `clean_data` and `read_data` lack generality to be re-used in different context (-2)
- [ ] Please improve the coverage of unit tests. For example, addition to testing if `clean_data` returns a data frame with correct column names, you should also test if the values in data frame matches (-2)
- [ ] Please remove the unnecessary output files, i.e. `.Rhistory` and `.DS_Store` inside the repository (-1)
- [ ] Please implement milestone feature on Github to track the process (-2)
- [ ] Please ensure every feature & fix to be operated under a separate branch, and merge into the main branch using pull requests (-1)
