### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by gzzen** [calamari99/dsci-310-group-12-dreamteam#3]
Below is a list of feedback that you can make use of to improve your project. If anything is unclear, please feel free to ask questions under this issue thread. We are looking forward to see your next milestone!

### README.md

- [x] Please improve one or more incomplete documentation (i.e., project title, other group members' names, license) (-1)

- [x] Clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present) (-1)
- [ ] Please provide the instruction of how to run the project reproducibly in the documentation (-6)

### Github release

- [ ] Please create a Github release with correct version number. You can refer to [[how to create a release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) (-5)

### Dockerfile

- [ ] Please create a Dockerfile that specifies and creates the Docker image to create an reproducible computational environment for your analysis (-10)

### Github action

- [ ] Please add a GitHub Actions workflow to automatically build the image, push it to DockerHub, and version the image (`lasted` is okay at this stage) when changes are pushed to the Dockerfile (-5)

### Project organization

- [ ] Please use Github issues for features, fixes, task tracking, and other project-related communications (-3)

- [ ] Please track the progress of the project using [[Github miltstones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones), and associate this funcationality with issues and pull requests (-2)
- [ ] Please make sufficient use of Github project board by associating Github issue cards into the board. The project board should show the current status of the project to the team. (-5)

### Project file and directory structure

- [ ] The directory structure of the repository can be improved by removing staging files (i.e., `.DS_Store`, `.Rhistory`, etc.). You should consider making use of the `.gitignore` file (-1)

### Analysis

- [ ] Please make appropriate adjustments to the report to make it different from the original DSCI 100 project (-0)

### Version control workflow

- [ ] Please ensure every feature & fix to be operated under a separate branch, and merge into the main branch using pull requests (-1)
